services:
  web:
    build:
      context: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && yarn install && bin/dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - bundle-data:/usr/local/bundle
      - node-modules:/myapp/node_modules
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bro_development
      - TZ=Asia/Tokyo
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
  node-modules:
  bundle-data:
